#!/bin/bash
echo "Hello, what is your name?"
#ssh digitalocean "python -c 'import db; ;'; echo hi"
ssh do "cd vigilant-web-gallery; python -c 'import utils; utils.printGalleries(utils.getAllGalleries);'"
echo "Please enter the number of the gallery you would like"
read gallery
ssh do "cd vigilant-web-gallery; python -c 'import utils; utils.printImages($gallery)'"



